### PR TITLE
Fixes crash in `installSourceNodeRemovalObserver `

### PR DESCRIPTION
**Pull request by cloudkite**
Was having the same problem as described in https://github.com/yahoo/react-dnd-touch-backend/issues/6

in some cases node passed to `installSourceNodeRemovalObserver` can be `null` which causes `node.parentElement` to throw

```
Uncaught TypeError: Cannot read property 'parentElement' of undefined

installSourceNodeRemovalObserver @ Touch.js:301
handleTopMoveCapture @ Touch.js:256
```

Adding this check fixes this issue, but wasn't sure if this check would be better earlier on maybe before `installSourceNodeRemovalObserver` is called?

### CODE REVIEW

**Comment by longlho** [comment]
@cloudkite thanks for the PR :) Can you clarify `in some cases node passed to installSourceNodeRemovalObserver can be null which causes node.parentElement to throw`? Do you happen to know under which circumstances this would happen?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by cloudkite** [comment]
@longlho I think it's when the item you are dragging is no longer in the DOM, ie dragging an item between two lists. Will try see if I can replicate with a stripped back example. Thanks

**Comment by cloudkite** [comment]
@longlho here is the minimum changes to example to replicate the issue. https://github.com/yahoo/react-dnd-touch-backend/compare/master...cloudkite:dragStartExample

basically I am removing the dragged item from its list as soon as the user starts dragging

**Comment by longlho** [comment]
@cloudkite ah thanks a lot for the example! I'll merge this and try to include your example as well in a separate commit

**Comment by cloudkite** [comment]
:+1:

Oh didn't realise you would want to update the example as well.  Was just a quick and dirty way to replicate issue, feel free to adapt as you see fit.

**Comment by cloudkite** [comment]
Also just saw I didn't run lint! Sorry!

**Comment by longlho** [comment]
np tks for the PR :)

**Pull request closed without merging**
