### PR TITLE
Add mouse events support

### PR DESCRIPTION
**Pull request by methyl**
This PR is featuring https://github.com/yahoo/react-dnd-touch-backend/issues/7

### CODE REVIEW

**Comment by longlho** [comment]
awesome! :clap: I'll verify asap :)

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by longlho** [comment]
merged w/ some minor fixes :) Thanks a lot! :+1:

**Comment by methyl** [comment]
@longlho thanks for the fixes!

**Pull request closed without merging**
