### PR TITLE
Cancel drag by hitting Escape 

### PR DESCRIPTION
**Pull request by oyshan**
Enable keyboard events (cancel drag by hitting ESC) by configuring touch backend as follows:
`DragDropContext(TouchBackend({ enableKeyboardEvents: true }));`

If enableKeyboardEvents option is set to true, the user will be able to cancel a drag event by hitting the Escape key.

The reason for why one should support keyboard interaction on touch backend is because there are cases where we're not really using touch devices. E.g. if you embed a chromium browser in .NET, this browser, for some reason (at least in my experience), is touch enabled..don't ask me why

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by longlho** [comment]
👍

**Comment by longlho** [comment]
`0.3.5` published

**Pull request merged**
