### PR TITLE
Allow invoking hover when source node is still over drop target

### PR DESCRIPTION
**Pull request by xhubbsaxo**
For cases when no preview is used we would like to have option to receive hover in drop target when source node is still over drop target and pointer is outside of it.

Currently hover is not invoked when drag is started source is still over target and mouse is moved.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by xhubbsaxo** [comment]
Hi, @longlho can you please have a look?

**Comment by longlho** [comment]
LMK when the diff's ready for review

**Comment by xhubbsaxo** [comment]
@longlho i think it's fine now... it took a while to go back to it anyway:

1. Example is added
2. It's aligned with master

Additionally:

1. I've updated deps,  yarn.lock / package-lock.json updated
2. I've fixed npm run dev, added some simple dev server
3. I've moved default example to sortableLists folder
4. I've updated package.json scripts
5. Removed some dead code from Touch.js
6. Updated Readme with installation steps for npm and yarn etc..
7. Updated import in examples
8. Some other minor cleanups in examples

Happy reading...

**Comment by longlho** [comment]
thanks! published as 0.8

**Comment by cormacrelf** [comment]
People have been wanting to do this for years, so good work @xhubbsaxo. Here are some notes for people who can't quite see how it works immediately:

A quick read reveals it is DOM [`Node.contains`](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) that determines whether hover will still fire, which is different from "over" as the term is normally used -- there is no hit testing here, you have to keep the drag source node inside the target's DOM node.

It appears (without testing) that multiple nested parent drop targets will all fire if this condition is met -- presumably in the expected order.

The example's CSS looks like black magic, and as usual for CSS, that's because it is:
* The parent list is position: relative, and so are the children. The first list item is relative *to* the parent; the rest are relative to their preceding sibling's pre-shifted position. Yes, CSS positioning is weird.
* The code simply updates a `top: 123px` property on:
  * The drag source, whose top follows the mouse displacement
  * Any elements that need to be shifted `+-$height` to accommodate
* The `top` values do not affect the relative position of the elements that come after.

All this raises one question for me: **does this code hold up to a usage pattern where DOM nodes are moved around within a parent, instead of CSS-shifted, and each item has a drop target?** It looks like it doesn't.

* The example depends on the drop target being the container and having uniform or at least known item heights in `px`:

https://github.com/yahoo/react-dnd-touch-backend/blob/aad39fac58270f28b4d088b5acc074814e114403/examples/hoverOutside/js/List.jsx#L52-L53

* If you followed the classic method of having one drop target per list item, none of them would `Node.contains(sourceNode)`.

If you're trying to make this locked sortable, a more obvious way to achieve axis locking without studying years at the CSS monastery is to use a custom drag layer, and draw custom drag previews with only one of x or y displacement passed down. You will still be limited to uniform/known item heights, but that's not so bad for the UI patterns that really benefit from this feature.

There are a few API additions (possibly higher level than the backend, so it could be configured differently for different parts of an app) that might support more usage patterns here. Making `targetNode.contains(sourceNode)` a configurable function `shouldHover(targetNode, sourceNode): bool` somewhere in the API might help. This is the exact point at which react-beautiful-dnd diverged -- using weighted hit testing just wasn't possible. That signature might not be sufficient -- you might want to pick out of many options which target(s) is/are the best ones to fire hover on. I'm not sure how bubbling should work, or how it could remain fast.

**Comment by xhubbsaxo** [comment]
@cormacrelf thx for feedback. I will analyze it and go back to you in couple of days. The first very quick question would be:

Are other examples correct? From my point of view List itself is a drop target . Having drop target on each of the items means that you would like to drag one item into inside of second one(or just drag sth into the item itself) right?

**Comment by cormacrelf** [comment]
I'm really pointing to this, the canonical way of building it: http://react-dnd.github.io/react-dnd/examples/sortable/simple

The hover handler checks which half of the list item you're hovering on, and might trigger a reorder.

It also happens to be the basis for [`@angular-skyhook/sortable`](https://cormacrelf.github.io/angular-skyhook/sortable/), which I wrote.

**Pull request merged**
