### PR TITLE
fix: handle null node when iterating over SVG elements

### PR DESCRIPTION
**Pull request by jacazek**
IE encounters errors if the mouse is over an SVG element while dragging any source.  This change accounts for the null value encountered while iterating over the ancestors of the SVG element.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by jacazek** [comment]
Agreement signed.

**Comment by longlho** [comment]
thanks!

**Comment by longlho** [comment]
`0.3.14` published @jacazek can u verify?

**Comment by jacazek** [comment]
I have verified this change is in place.  Thanks for merging.

**Pull request merged**
